### ISSUE TITLE
Warning in MaxPQ class

### ISSUE THREAD

**Issue by ozneroL541** [ozneroL541/Climate_Monitoring#36]
Even if the program execute correctly I recive some **warnings** in class `MaxPQ` because of the use of `Comparable` parameters.
The class must remains parametric and execute in the same way, but without **warnings**.

#Reseach

**Comment by ozneroL541** [comment]
Non è che non voglio vedere gli avvertimenti, voglio che non ci siano.

**Comment by ozneroL541** [comment]
Ho recentemente creato un branch derivato da quello in questione al fine di dare una visione più chiara e pulita del problema. La classe MaxPQ in tale branch è nel suo stato originale, prima che gli venissero apportati cambiamenti per tentare di eliminare alcuni Warnings.

**Comment by Giaki03** [comment]
Sembrerebbe che avere un array di oggetti generici che implementino tutti una interfaccia sia impossibile. Per di più usare i tipi parametrizzati sembrerebbe cattiva pratica, visto che esistono per garantire la retrocompatibilità con vecchie versioni di Java.
Fonti: 
https://stackoverflow.com/questions/2770321/what-is-a-raw-type-and-why-shouldnt-we-use-it
https://stackoverflow.com/questions/1817524/generic-arrays-in-java

**Comment by Giaki03** [comment]
Se MaxPQ userà, nel pratico, solo oggetti della classe Distance suggerisco di utilizzare Comparable<Distance> e fare controlli sulla classe degli oggetti. Si potrebbe fare una classe, che implementa Comparable, la quale viene ereditata da tutte le classi che intendi utilizzare in MaxPQ. Andrebbe, tuttavia, controllato che ogni oggetto inserito in MaxPQ sia sottoclasse di questa nuova classe.
Dimmi se può andare bene come soluzione.

**Comment by ozneroL541** [comment]
> Sembrerebbe che avere un array di oggetti generici che implementino tutti una interfaccia sia impossibile. Per di più usare i tipi parametrizzati sembrerebbe cattiva pratica, visto che esistono per garantire la retrocompatibilità con vecchie versioni di Java. Fonti: https://stackoverflow.com/questions/2770321/what-is-a-raw-type-and-why-shouldnt-we-use-it https://stackoverflow.com/questions/1817524/generic-arrays-in-java

Non c'è scritto in nessuna delle due fonti che usare classi parametriche è una cattiva pratica. Lo è solo se non ne si definisce il parametro quando si crea l'oggetto.

**Comment by ozneroL541** [comment]
> Se MaxPQ userà, nel pratico, solo oggetti della classe Distance suggerisco di utilizzare Comparable e fare controlli sulla classe degli oggetti. Si potrebbe fare una classe, che implementa Comparable, la quale viene ereditata da tutte le classi che intendi utilizzare in MaxPQ. Andrebbe, tuttavia, controllato che ogni oggetto inserito in MaxPQ sia sottoclasse di questa nuova classe. Dimmi se può andare bene come soluzione.

Non si capisce, riformula.
Usare `Comparable` come?
Cosa intendi per "_fare controlli sulla classe degli oggetti_"?
`Dinstance` implementa già Comparable.

**Comment by Giaki03** [comment]
L'unico modo per far si che quella classe funzioni con oggetti generici è utilizzare la classe Object, dalla quale ogni altra classe in java ne è figlia, ma Object non implementa Comparable e quindi non può utilizzare il compareTo.

**Comment by Giaki03** [comment]
> > Sembrerebbe che avere un array di oggetti generici che implementino tutti una interfaccia sia impossibile. Per di più usare i tipi parametrizzati sembrerebbe cattiva pratica, visto che esistono per garantire la retrocompatibilità con vecchie versioni di Java. Fonti: https://stackoverflow.com/questions/2770321/what-is-a-raw-type-and-why-shouldnt-we-use-it https://stackoverflow.com/questions/1817524/generic-arrays-in-java
> 
> Non c'è scritto in nessuna delle due fonti che usare classi parametriche è una cattiva pratica. Lo è solo se non ne si definisce il parametro quando si crea l'oggetto.

E infatti i warning si riferiscono a quello.
