### ISSUE TITLE
Visibiltà delle classi Menu

### ISSUE THREAD

**Issue by Giaki03** [ozneroL541/Climate_Monitoring#37]
Le classi MenuOperator e MenuCentre sono state dichiarate con visibilità package, ma i loro attributi e i metodi che vengono esposti sono invece protected. Non sarebbe meglio cambiare da protected a package, perché, per come è adesso, queste classi sono visibili da tutte le sottoclassi di User, anche eventuali classi in altri package (cosa che attualmente non è vera). Se si cambiasse la visibilità a package le due classi menu sarebbero visibili esclusivamente dalle classi del package Users.
Non cambierebbe nulla, è sola una questione di sicurezza.

**Comment by ozneroL541** [comment]
`protected` per i campi e i metodi corrisponde alla visibilità `package` per le classi.
